var annotated_dup =
[
    [ "AOS", "d6/d26/class_a_o_s.html", "d6/d26/class_a_o_s" ],
    [ "Classifier", "d6/dba/class_classifier.html", "d6/dba/class_classifier" ],
    [ "Data", "dc/d07/class_data.html", "dc/d07/class_data" ],
    [ "DualClassifier", "d1/dbb/class_dual_classifier.html", "d1/dbb/class_dual_classifier" ],
    [ "FeatureSelection", "df/d2f/class_feature_selection.html", "df/d2f/class_feature_selection" ],
    [ "Fisher", "d5/d3f/class_fisher.html", "d5/d3f/class_fisher" ],
    [ "Gnuplot", "d3/d27/class_gnuplot.html", "d3/d27/class_gnuplot" ],
    [ "GnuplotException", "d1/dd4/class_gnuplot_exception.html", "d1/dd4/class_gnuplot_exception" ],
    [ "Golub", "d8/d9c/class_golub.html", "d8/d9c/class_golub" ],
    [ "IMADual", "d6/da4/class_i_m_a_dual.html", "d6/da4/class_i_m_a_dual" ],
    [ "IMAp", "dd/de8/class_i_m_ap.html", "dd/de8/class_i_m_ap" ],
    [ "IMApFixedMargin", "df/db6/class_i_m_ap_fixed_margin.html", "df/db6/class_i_m_ap_fixed_margin" ],
    [ "int_dll", "df/d98/structint__dll.html", "df/d98/structint__dll" ],
    [ "Kernel", "db/de7/class_kernel.html", "db/de7/class_kernel" ],
    [ "Learner", "d9/d2a/class_learner.html", "d9/d2a/class_learner" ],
    [ "PerceptronDual", "d7/db4/class_perceptron_dual.html", "d7/db4/class_perceptron_dual" ],
    [ "PerceptronFixedMarginDual", "d6/d4e/class_perceptron_fixed_margin_dual.html", "d6/d4e/class_perceptron_fixed_margin_dual" ],
    [ "PerceptronFixedMarginPrimal", "d5/d40/class_perceptron_fixed_margin_primal.html", "d5/d40/class_perceptron_fixed_margin_primal" ],
    [ "PerceptronPrimal", "d8/d34/class_perceptron_primal.html", "d8/d34/class_perceptron_primal" ],
    [ "Point", "d0/d69/class_point.html", "d0/d69/class_point" ],
    [ "PrimalClassifier", "db/d87/class_primal_classifier.html", "db/d87/class_primal_classifier" ],
    [ "RFE", "d8/dd3/class_r_f_e.html", "d8/dd3/class_r_f_e" ],
    [ "SMO", "d8/de4/class_s_m_o.html", "d8/de4/class_s_m_o" ],
    [ "Solution", "dd/d4f/class_solution.html", "dd/d4f/class_solution" ],
    [ "Statistics", "d8/da8/class_statistics.html", "d8/da8/class_statistics" ],
    [ "Timer", "d8/d08/class_timer.html", "d8/d08/class_timer" ],
    [ "Validation", "dd/da7/class_validation.html", "dd/da7/class_validation" ],
    [ "ValidationSolution", "d5/df8/struct_validation_solution.html", "d5/df8/struct_validation_solution" ],
    [ "Visualization", "d0/d85/class_visualization.html", "d0/d85/class_visualization" ]
];